#!/bin/bash

# Where to install the tools. Note that this needs to be a filesystem that
# is capable of symlinks (not {NTFS,FAT*} filesystems).
GCC_ARM_PREFIX="/usr/local"
#GCC_ARM_PREFIX="/media/sf_mbed"

# These variables define the version of GCC ARM to download

# The 5.4 series isn't officially supported by mbed
#GCC_ARM="gcc-arm-none-eabi-5_4-2016q2"
#GCC_ARM_EXT="-20160622-linux.tar.bz2"
#GCC_ARM_BASE_URL="https://launchpad.net/gcc-arm-embedded/5.0/5-2016-q2-update/+download/"

GCC_ARM="gcc-arm-none-eabi-4_9-2015q3"
GCC_ARM_EXT="-20150921-linux.tar.bz2"
GCC_ARM_BASE_URL="https://launchpad.net/gcc-arm-embedded/4.9/4.9-2015-q3-update/+download/"

